# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='loadingfile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='price.LoadingFile'),
            preserve_default=False,
        ),
    ]
