# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_price_loadingfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.FloatField(),
        ),
    ]
