# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20170322_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name_views',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
